# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16glaMdaDCoZGV8FOGG5lksAUaTfl4ic8
"""

import pandas as pd
print ("pandas loaded successfully!")

# 1. Load the data
df = pd.read_csv ('netflix_titles.csv')

#2. view the first 5 rows to see what data field we have
df.head()

#check for missing data (nulll values)
df.isnull().sum()

#fill massive missing block with unknown
df ['director'] =df ['director'].fillna('unknown')
df ['cast'] = df ['cast'].fillna('unknown')
df ['country'] = df ['country'].fillna('unknown')

#drop rows where crtitical column have missing value
df = df.dropna (subset=['data_added', 'rating', 'duration'])

#drop rows where crtitical column have missing value
df = df.dropna (subset=['date_added', 'rating', 'duration'])

df.isnull().sum()

df.head()

df['type'].value_counts()

# 1. Strip extra spaces and convert the text colum into clean Date format
df ['date_added']= pd.to_datetime(df['date_added'].str.strip())

#2. Extract Year and Month into seperate columns for deep slicing
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.strftime('%B')

#3. View our new columns to make sure it worked
df[['date_added, 'year_added', 'month_added]].head()

# 1. Strip extra spaces and convert the text colum into clean Date format
df ['date_added']= pd.to_datetime(df['date_added'].str.strip())

#2. Extract Year and Month into seperate columns for deep slicing
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.strftime('%B')

#3. View our new columns to make sure it worked
df[['date_added', 'year_added', 'month_added]].head()

# 1. Strip extra spaces and convert the text colum into clean Date format
df ['date_added']= pd.to_datetime(df['date_added'].str.strip())

#2. Extract Year and Month into seperate columns for deep slicing
df['year_added'] = df['date_added'].dt.year
df['month_added'] = df['date_added'].dt.strftime('%B')

#3. View our new columns to make sure it worked
df[['date_added', 'year_added', 'month_added']].head()

df.to_csv('netflix_clean.csv', index=False)
print("your clean dataset is ready!")

